# Ygtm (Yellow Google Tag Manager) for Datenstrom Yellow 
# Extension settings

Extension: Ygtm
Version: 0.9.3
Status: experimental
Description: Ygtm is a cookie consent extension for the Google Tag Manager.
DocumentationUrl: https://github.com/PetersOtto/yellow-ygtm
DownloadUrl: https://github.com/PetersOtto/yellow-ygtm/archive/refs/heads/main.zip
Published: 2026-03-31 23:55:00
Designer: PetersOtto
Tag: Google Tag Manager

system/workers/ygtm.php: ygtm.php, create, update
